database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:root}
database.name = ${DB_DBNAME:measurement}

spring.datasource.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true

###############################################
### MICROSERVICE CONFIGURATIONS ###
###############################################
device.service.url=${DEVICE_SERVICE_URL:http://localhost:8082}

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.ro.tuc=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8082}
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.connection-timeout=5000

# Enable response compression
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain

# Enable cors
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*

###########
#####rabbit
###########
# RabbitMQ configuration
spring.rabbitmq.host=rat.rmq2.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=qzwqpbut
spring.rabbitmq.password=C9czddqHxrh-cLELUuCiiFgesCdbCU-G
spring.rabbitmq.virtual-host=qzwqpbut